site_name: Programa Tarjetas Electr贸nicas - ESP32 - Arduino
site_description: "Documentaci贸n Programa Tarjetas Electr贸nicas con ESP32 Arduino- Mecatr贸nica 85"
site_author: Alejandro Leyva
site_url: https://www.alejandro-leyva.com/micro-esp32
edit_uri: ""

theme:
  name: material
  locale: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: es
  features:
    - navigation.footer
    - content.code.copy

repo_url: https://github.com/jalmx/micro-esp32

markdown_extensions:
  - tables
  - meta
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/footer.js
  - javascripts/change_height_markmap.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/d3@6.7.0/dist/d3.min.js
  - https://unpkg.com/markmap-lib@0.11.6/dist/browser/index.min.js
  - https://unpkg.com/markmap-view@0.2.6/dist/index.min.js

extra:
  homepage: https://www.alejandro-leyva.com/algoritmos/
  version: 1.0

  copyright: "Alejandro Leyva 2022 - 2024"

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jalmx
    - icon: fontawesome/brands/dev
      link: https://www.alejandro-leyva.com
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/mecatronica85/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@xizuth
    - icon: fontawesome/solid/paper-plane
      link: mailto:alejandro.leyva.us@gmail.com

plugins:
  - search:
      lang: es
      indexing: 'full'
  # - minify:
  #     minify_html: true